# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import robot_pb2 as robot__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotServiceStub(object):
    """*
    Unified service (no CameraBackend enum; uses oneof to select RS / V4L2).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlVideo = channel.unary_unary(
                '/robot.RobotService/ControlVideo',
                request_serializer=robot__pb2.ControlSignalRequest.SerializeToString,
                response_deserializer=robot__pb2.ControlSignalResponse.FromString,
                _registered_method=True)
        self.ControlAudio = channel.unary_unary(
                '/robot.RobotService/ControlAudio',
                request_serializer=robot__pb2.ControlSignalRequest.SerializeToString,
                response_deserializer=robot__pb2.ControlSignalResponse.FromString,
                _registered_method=True)
        self.VRStream = channel.stream_unary(
                '/robot.RobotService/VRStream',
                request_serializer=robot__pb2.VRFrame.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RecorderReinit = channel.unary_unary(
                '/robot.RobotService/RecorderReinit',
                request_serializer=robot__pb2.RecorderReinitRequest.SerializeToString,
                response_deserializer=robot__pb2.RecorderReinitReply.FromString,
                _registered_method=True)
        self.RecorderGetState = channel.unary_unary(
                '/robot.RobotService/RecorderGetState',
                request_serializer=robot__pb2.RecorderGetStateRequest.SerializeToString,
                response_deserializer=robot__pb2.RecorderGetStateReply.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """*
    Unified service (no CameraBackend enum; uses oneof to select RS / V4L2).
    """

    def ControlVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VRStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecorderReinit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecorderGetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlVideo,
                    request_deserializer=robot__pb2.ControlSignalRequest.FromString,
                    response_serializer=robot__pb2.ControlSignalResponse.SerializeToString,
            ),
            'ControlAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlAudio,
                    request_deserializer=robot__pb2.ControlSignalRequest.FromString,
                    response_serializer=robot__pb2.ControlSignalResponse.SerializeToString,
            ),
            'VRStream': grpc.stream_unary_rpc_method_handler(
                    servicer.VRStream,
                    request_deserializer=robot__pb2.VRFrame.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RecorderReinit': grpc.unary_unary_rpc_method_handler(
                    servicer.RecorderReinit,
                    request_deserializer=robot__pb2.RecorderReinitRequest.FromString,
                    response_serializer=robot__pb2.RecorderReinitReply.SerializeToString,
            ),
            'RecorderGetState': grpc.unary_unary_rpc_method_handler(
                    servicer.RecorderGetState,
                    request_deserializer=robot__pb2.RecorderGetStateRequest.FromString,
                    response_serializer=robot__pb2.RecorderGetStateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """*
    Unified service (no CameraBackend enum; uses oneof to select RS / V4L2).
    """

    @staticmethod
    def ControlVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/ControlVideo',
            robot__pb2.ControlSignalRequest.SerializeToString,
            robot__pb2.ControlSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/ControlAudio',
            robot__pb2.ControlSignalRequest.SerializeToString,
            robot__pb2.ControlSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VRStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robot.RobotService/VRStream',
            robot__pb2.VRFrame.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecorderReinit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/RecorderReinit',
            robot__pb2.RecorderReinitRequest.SerializeToString,
            robot__pb2.RecorderReinitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecorderGetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/RecorderGetState',
            robot__pb2.RecorderGetStateRequest.SerializeToString,
            robot__pb2.RecorderGetStateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
